### Problem Statement:

**Predict whether a patient will be readmitted to the hospital within 30 days after discharge.**

In [7]:
import pandas as pd
import numpy as np
df=pd.read_csv('../data/raw/diabetic_data.csv',)

In [16]:
df.head().iloc[:,9:]

,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,diag_1,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,1,NaN,Pediatrics-Endocrinology,41,0,1,0,0,0,250.83,...,No,No,No,No,No,No,No,No,No,NO
1,3,NaN,NaN,59,0,18,0,0,0,276,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,2,NaN,NaN,11,5,13,2,0,1,648,...,No,No,No,No,No,No,No,No,Yes,NO
3,2,NaN,NaN,44,1,16,0,0,0,8,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,1,NaN,NaN,51,0,8,0,0,0,197,...,No,Steady,No,No,No,No,No,Ch,Yes,NO

In [30]:
df.replace('?',np.nan,inplace=True)

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,medical_specialty,num_lab_procedures,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,Caucasian,Female,[0-10),6,25,1,1,NaN,Pediatrics-Endocrinology,41,...,No,No,No,No,No,No,No,No,No,0
1,Caucasian,Female,[10-20),1,1,7,3,NaN,NaN,59,...,No,Up,No,No,No,No,No,Ch,Yes,0
2,AfricanAmerican,Female,[20-30),1,1,7,2,NaN,NaN,11,...,No,No,No,No,No,No,No,No,Yes,0
3,Caucasian,Male,[30-40),1,1,7,2,NaN,NaN,44,...,No,Up,No,No,No,No,No,Ch,Yes,0
4,Caucasian,Male,[40-50),1,1,7,1,NaN,NaN,51,...,No,Steady,No,No,No,No,No,Ch,Yes,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,AfricanAmerican,Male,[70-80),1,3,7,3,MC,NaN,51,...,No,Down,No,No,No,No,No,Ch,Yes,0
101762,AfricanAmerican,Female,[80-90),1,4,5,5,MC,NaN,33,...,No,Steady,No,No,No,No,No,No,Yes,0
101763,Caucasian,Male,[70-80),1,1,7,1,MC,NaN,53,...,No,Down,No,No,No,No,No,Ch,Yes,0
101764,Caucasian,Female,[80-90),2,3,7,10,MC,Surgery-General,45,...,No,Up,No,No,No,No,No,Ch,Yes,0
101765,Caucasian,Male,[70-80),1,1,7,6,NaN,NaN,13,...,No,No,No,No,No,No,No,No,No,0

In [23]:
df['readmitted'].unique()

<StringArray>
['NO', '>30', '<30']
Length: 3, dtype: str

`readmitted` is my target.

We want to find the patients who readmitted in one month - <30

**{'NO':0,  '>30':0,  '<30':1}**

In [28]:
df['readmitted']=df['readmitted'].replace({'NO':0,'>30':0,'<30':1}).astype(int)

In [29]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 45 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   race                      99493 non-null   str
 1   gender                    101766 non-null  str
 2   age                       101766 non-null  str
 3   admission_type_id         101766 non-null  int64
 4   discharge_disposition_id  101766 non-null  int64
 5   admission_source_id       101766 non-null  int64
 6   time_in_hospital          101766 non-null  int64
 7   payer_code                61510 non-null   str
 8   medical_specialty         51817 non-null   str
 9   num_lab_procedures        101766 non-null  int64
 10  num_procedures            101766 non-null  int64
 11  num_medications           101766 non-null  int64
 12  number_outpatient         101766 non-null  int64
 13  number_emergency          101766 non-null  int64
 14  number_inpatient          101766 non-null  int64
 15  diag_1                    101745 non-null  str
 16  diag_2                    101408 non-null  str
 17  diag_3                    100343 non-null  str
 18  number_diagnoses          101766 non-null  int64
 19  metformin                 101766 non-null  str
 20  repaglinide               101766 non-null  str
 21  nateglinide               101766 non-null  str
 22  chlorpropamide            101766 non-null  str
 23  glimepiride               101766 non-null  str
 24  acetohexamide             101766 non-null  str
 25  glipizide                 101766 non-null  str
 26  glyburide                 101766 non-null  str
 27  tolbutamide               101766 non-null  str
 28  pioglitazone              101766 non-null  str
 29  rosiglitazone             101766 non-null  str
 30  acarbose                  101766 non-null  str
 31  miglitol                  101766 non-null  str
 32  troglitazone              101766 non-null  str
 33  tolazamide                101766 non-null  str
 34  examide                   101766 non-null  str
 35  citoglipton               101766 non-null  str
 36  insulin                   101766 non-null  str
 37  glyburide-metformin       101766 non-null  str
 38  glipizide-metformin       101766 non-null  str
 39  glimepiride-pioglitazone  101766 non-null  str
 40  metformin-rosiglitazone   101766 non-null  str
 41  metformin-pioglitazone    101766 non-null  str
 42  change                    101766 non-null  str
 43  diabetesMed               101766 non-null  str
 44  readmitted                101766 non-null  int64
dtypes: int64(12), str(33)
memory usage: 34.9 MB

In [21]:
df.isnull().mean()*100

race                         2.233555
gender                       0.000000
age                          0.000000
admission_type_id            0.000000
discharge_disposition_id     0.000000
admission_source_id          0.000000
time_in_hospital             0.000000
payer_code                  39.557416
medical_specialty           49.082208
num_lab_procedures           0.000000
num_procedures               0.000000
num_medications              0.000000
number_outpatient            0.000000
number_emergency             0.000000
number_inpatient             0.000000
diag_1                       0.020636
diag_2                       0.351787
diag_3                       1.398306
number_diagnoses             0.000000
metformin                    0.000000
repaglinide                  0.000000
nateglinide                  0.000000
chlorpropamide               0.000000
glimepiride                  0.000000
acetohexamide                0.000000
glipizide                    0.000000
glyburide                    0.000000
tolbutamide                  0.000000
pioglitazone                 0.000000
rosiglitazone                0.000000
acarbose                     0.000000
miglitol                     0.000000
troglitazone                 0.000000
tolazamide                   0.000000
examide                      0.000000
citoglipton                  0.000000
insulin                      0.000000
glyburide-metformin          0.000000
glipizide-metformin          0.000000
glimepiride-pioglitazone     0.000000
metformin-rosiglitazone      0.000000
metformin-pioglitazone       0.000000
change                       0.000000
diabetesMed                  0.000000
readmitted                   0.000000
dtype: float64

`enouter_id`,`patient_nbr` is just id so we can drop them. 

`weight`, `max_glu_serum`,`A1Cresult` contains null values close to 90% so imputing it will introduce bias only. So lets drop them also

In [19]:
cols_to_drop = ['encounter_id', 'patient_nbr', 'weight', 'max_glu_serum', 'A1Cresult']
numerical_cols=['']
categorical_cols=['race','gender','age','admission_type_id','discharge_disposition_id','admission_source_id','time_in_hospital',
                 '']

In [20]:
df.isnull().mean()*100

race                         2.233555
gender                       0.000000
age                          0.000000
admission_type_id            0.000000
discharge_disposition_id     0.000000
admission_source_id          0.000000
time_in_hospital             0.000000
payer_code                  39.557416
medical_specialty           49.082208
num_lab_procedures           0.000000
num_procedures               0.000000
num_medications              0.000000
number_outpatient            0.000000
number_emergency             0.000000
number_inpatient             0.000000
diag_1                       0.020636
diag_2                       0.351787
diag_3                       1.398306
number_diagnoses             0.000000
metformin                    0.000000
repaglinide                  0.000000
nateglinide                  0.000000
chlorpropamide               0.000000
glimepiride                  0.000000
acetohexamide                0.000000
glipizide                    0.000000
glyburide                    0.000000
tolbutamide                  0.000000
pioglitazone                 0.000000
rosiglitazone                0.000000
acarbose                     0.000000
miglitol                     0.000000
troglitazone                 0.000000
tolazamide                   0.000000
examide                      0.000000
citoglipton                  0.000000
insulin                      0.000000
glyburide-metformin          0.000000
glipizide-metformin          0.000000
glimepiride-pioglitazone     0.000000
metformin-rosiglitazone      0.000000
metformin-pioglitazone       0.000000
change                       0.000000
diabetesMed                  0.000000
readmitted                   0.000000
dtype: float64