In [1]:
import pandas as pd
import os
import sys
import warnings
import yaml

import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.pipeline import Pipeline
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import precision_score, accuracy_score, f1_score, classification_report
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
from sklearn.model_selection import GridSearchCV

warnings.filterwarnings('ignore')
pd.set_option('display.max_columns',None)

## Load Data

In [2]:
CONFIG_PATH = '../configs/paths.yaml'

with open(CONFIG_PATH,"r") as file:
    paths = yaml.safe_load(file)

df_train = pd.read_csv(paths['features_data']['train_data'])
df_test  = pd.read_csv(paths['features_data']['test_data'])

print(f"Train shape: {df_train.shape}")
print(f"Test shape : {df_test.shape}")
df_train.head()

Train shape: (81477, 37)
Test shape : (20289, 37)

,race,gender,age,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,payer_code,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses,metformin,repaglinide,nateglinide,chlorpropamide,glimepiride,glipizide,glyburide,pioglitazone,rosiglitazone,acarbose,insulin,glyburide-metformin,glipizide-metformin,change,diabetesMed,diag_1_group,diag_2_group,diag_3_group,medical_specialty_group,total_prior_visits,high_utilizer,readmitted_binary
0,Caucasian,Female,0,6,25,1,1,Unknown,41,0,1,0,0,0,1,No,No,No,No,No,No,No,No,No,No,0,No,No,No,No,Diabetes,Unknown,Unknown,Pediatrics,0,0,0
1,Caucasian,Female,1,1,1,7,3,Unknown,59,0,18,0,0,0,9,No,No,No,No,No,No,No,No,No,No,3,No,No,Yes,Yes,Other,Diabetes,Other,Missing,0,0,0
2,AfricanAmerican,Female,2,1,1,7,2,Unknown,11,5,13,2,0,1,6,No,No,No,No,No,Yes,No,No,No,No,0,No,No,No,Yes,Other,Diabetes,Other,Missing,3,1,0
3,Caucasian,Male,3,1,1,7,2,Unknown,44,1,16,0,0,0,7,No,No,No,No,No,No,No,No,No,No,3,No,No,Yes,Yes,Other,Diabetes,Circulatory,Missing,0,0,0
4,Caucasian,Male,5,2,1,2,3,Unknown,31,6,16,0,0,0,9,No,No,No,No,No,No,No,No,No,No,1,No,No,No,Yes,Circulatory,Circulatory,Diabetes,Missing,0,0,0

In [3]:
X_train = df_train.drop(columns = ['readmitted_binary'])
X_test = df_test.drop(columns = ['readmitted_binary'])
y_train = df_train['readmitted_binary']
y_test = df_test['readmitted_binary']

# Preprocessor and Helper Function

In [4]:
sys.path.append(os.path.abspath('..'))

from scripts.preprocessor import get_preprocessor
from scripts.evaluate import evaluate_classifier

preprocessor = get_preprocessor()

In [5]:
pipeline = Pipeline(
    [
        ('preprocessor', preprocessor),
        ('random_forest', RandomForestClassifier(random_state=30,class_weight='balanced'))
    ]
)

In [6]:
result = evaluate_classifier('Random Forest',pipeline,X_train,X_test,y_train,y_test)

In [7]:
print(classification_report(y_test, result['_test_pred']))
result_df = pd.DataFrame([result]).drop(columns=['_pipeline', '_test_pred','_test_prob'])
result_df

              precision    recall  f1-score   support

           0       0.90      0.99      0.94     18120
           1       0.39      0.06      0.10      2169

    accuracy                           0.89     20289
   macro avg       0.64      0.52      0.52     20289
weighted avg       0.84      0.89      0.85     20289

,Model,Train Accuracy,Train Precision,Train Recall,Train F1,Test Accuracy,Test Precision,Test Recall,Test F1,Test_ROC_AUC_Score
0,Random Forest,0.9999,0.9991,1.0,0.9996,0.8897,0.3903,0.0558,0.0976,0.668488

### Why is Test Recall so low (0.0558) even with `class_weight='balanced'`?

Looking at the summary table above, we can see textbook evidence of **extreme overfitting**:
* **Train Recall:** 1.0 (100%)
* **Train Accuracy:** 0.9999 (99.99%)
* **Test Recall:** 0.0558 (5.5%)

Because the `RandomForestClassifier` was initialized with default parameters, the individual Decision Trees inside the forest were allowed to grow completely unchecked. They split and split until almost every single leaf node became **pure** (containing only 1 or 2 specific patients from the training set). 

#### The Class Weight Trap
The `class_weight='balanced'` parameter works by altering the probability math inside **mixed** leaf nodes (making minority class 1 patients mathematically "heavier" so they pull the node's probability over the 50% threshold). 

However, because our trees grew deep enough to perfectly memorize the data, there are virtually no mixed leaf nodes left for the class weights to act upon. A pure leaf node containing 1 Readmitted patient is already at 100% probability; multiplying its weight doesn't change its prediction. The model has just memorized training noise, which completely breaks its ability to generalize and catch readmissions on the unseen test set.

To fix this, we must apply "brakes" to the trees. By forcing the leaves to remain mixed, we allow the balanced class weights to finally do their job.

In [8]:
param_grid = {
    "random_forest__max_depth": [5, 10, 15, None],
    "random_forest__min_samples_leaf": [10, 30, 50, 100],
    "random_forest__n_estimators": [100, 200]
}

In [9]:
grid = GridSearchCV(
    estimator = pipeline,
    param_grid = param_grid,
    scoring = 'f1',
    cv = 5
)

In [10]:
grid.fit(X_train,y_train)

GridSearchCV(cv=5,
             estimator=Pipeline(steps=[('preprocessor',
                                        ColumnTransformer(remainder='passthrough',
                                                          transformers=[('scaler',
                                                                         StandardScaler(),
                                                                         ['time_in_hospital',
                                                                          'num_lab_procedures',
                                                                          'num_procedures',
                                                                          'num_medications',
                                                                          'number_outpatient',
                                                                          'number_emergency',
                                                                          'number_inpatient',
                                                                          'number_diagnoses',
                                                                          'total_prior_visits']),
                                                                        ('encoder',
                                                                         OneHotEncoder(drop='...
                                                                          'glipizide',
                                                                          'glyburide',
                                                                          'pioglitazone',
                                                                          'rosiglitazone',
                                                                          'acarbose',
                                                                          'glyburide-metformin',
                                                                          'glipizide-metformin'])])),
                                       ('random_forest',
                                        RandomForestClassifier(class_weight='balanced',
                                                               random_state=30))]),
             param_grid={'random_forest__max_depth': [5, 10, 15, None],
                         'random_forest__min_samples_leaf': [10, 30, 50, 100],
                         'random_forest__n_estimators': [100, 200]},
             scoring='f1')

In [11]:
grid.best_estimator_

Pipeline(steps=[('preprocessor',
                 ColumnTransformer(remainder='passthrough',
                                   transformers=[('scaler', StandardScaler(),
                                                  ['time_in_hospital',
                                                   'num_lab_procedures',
                                                   'num_procedures',
                                                   'num_medications',
                                                   'number_outpatient',
                                                   'number_emergency',
                                                   'number_inpatient',
                                                   'number_diagnoses',
                                                   'total_prior_visits']),
                                                 ('encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignor...
                                                   'gender', 'change',
                                                   'diabetesMed', 'metformin',
                                                   'repaglinide', 'nateglinide',
                                                   'chlorpropamide',
                                                   'glimepiride', 'glipizide',
                                                   'glyburide', 'pioglitazone',
                                                   'rosiglitazone', 'acarbose',
                                                   'glyburide-metformin',
                                                   'glipizide-metformin'])])),
                ('random_forest',
                 RandomForestClassifier(class_weight='balanced', max_depth=15,
                                        min_samples_leaf=10, n_estimators=200,
                                        random_state=30))])